CREATE TABLE upload_sessions (
  id VARCHAR(36) PRIMARY KEY,
  filename VARCHAR(255) NOT NULL,
  content_type VARCHAR(128) NOT NULL,
  size_bytes BIGINT NOT NULL,
  chunk_size INTEGER NOT NULL,
  status VARCHAR(24) NOT NULL,
  video_id VARCHAR(36),
  created_at TIMESTAMP NOT NULL
);
CREATE TABLE video_assets (
  id VARCHAR(36) PRIMARY KEY,
  sha256 VARCHAR(64) NOT NULL UNIQUE,
  size_bytes BIGINT NOT NULL,
  storage_path VARCHAR(1024) NOT NULL,
  duration_ms BIGINT,
  media_json TEXT,
  audio_path VARCHAR(1024),
  created_at TIMESTAMP NOT NULL
);
CREATE TABLE transcripts (
  video_id VARCHAR(36) PRIMARY KEY,
  sha256 VARCHAR(64) NOT NULL,
  segments_json TEXT NOT NULL,
  mode VARCHAR(24) NOT NULL,
  created_at TIMESTAMP NOT NULL
);
CREATE TABLE runs (
  id VARCHAR(36) PRIMARY KEY,
  video_id VARCHAR(36) NOT NULL,
  status VARCHAR(24) NOT NULL,
  owner VARCHAR(64),
  lease_until TIMESTAMP,
  budget_json TEXT NOT NULL,
  checkpoint_json TEXT NOT NULL,
  report_json TEXT,
  version VARCHAR(64),
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL
);
CREATE INDEX ix_runs_status_lease ON runs(status, lease_until);
CREATE TABLE node_executions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id VARCHAR(36) NOT NULL,
  node VARCHAR(128) NOT NULL,
  attempt INTEGER NOT NULL,
  status VARCHAR(24) NOT NULL,
  duration_ms BIGINT,
  output_json TEXT,
  error TEXT,
  UNIQUE(run_id, node, attempt)
);
CREATE TABLE trace_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id VARCHAR(36) NOT NULL,
  node VARCHAR(128),
  event_type VARCHAR(64) NOT NULL,
  payload_json TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL
);
CREATE TABLE outbox_events (
  id VARCHAR(36) PRIMARY KEY,
  event_key VARCHAR(128) NOT NULL UNIQUE,
  topic VARCHAR(128) NOT NULL,
  payload_json TEXT NOT NULL,
  published_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL
);
CREATE TABLE feedback (
  id VARCHAR(36) PRIMARY KEY,
  run_id VARCHAR(36) NOT NULL,
  label VARCHAR(32) NOT NULL,
  fingerprint VARCHAR(128) NOT NULL,
  note TEXT,
  created_at TIMESTAMP NOT NULL
);
CREATE TABLE evolution_versions (
  id VARCHAR(36) PRIMARY KEY,
  version VARCHAR(64) NOT NULL UNIQUE,
  status VARCHAR(24) NOT NULL,
  predecessor VARCHAR(64),
  candidate_json TEXT NOT NULL,
  validation_json TEXT NOT NULL,
  holdout_json TEXT NOT NULL,
  gate_decision VARCHAR(24) NOT NULL,
  created_at TIMESTAMP NOT NULL
);
